version: '3.8'

services:
  cambria-tracker:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/live-feed"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s