[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/wallet/*"
to = "/.netlify/functions/wallet-address"
status = 200
force = true

[dev]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
